import type { SurveyQuestion } from "@/types";

export const DEFAULT_WELLNESS_QUESTIONS: SurveyQuestion[] = [
  {
    id: "sleep_hours",
    label: "Hours of sleep last night",
    type: "scale",
    min: 4,
    max: 10,
    required: true,
    flag_below: 6,
  },
  {
    id: "sleep_quality",
    label: "Sleep quality",
    type: "scale",
    min: 1,
    max: 10,
    required: true,
    flag_below: 4,
  },
  {
    id: "energy",
    label: "Energy level",
    type: "scale",
    min: 1,
    max: 10,
    required: true,
    flag_below: 3,
  },
  {
    id: "soreness",
    label: "Muscle soreness",
    type: "scale",
    min: 1,
    max: 10,
    required: true,
    flag_above: 8,
  },
  {
    id: "stress",
    label: "Stress level",
    type: "scale",
    min: 1,
    max: 10,
    required: true,
    flag_above: 8,
  },
  {
    id: "mood",
    label: "Mood",
    type: "scale",
    min: 1,
    max: 10,
    required: true,
    flag_below: 3,
  },
  {
    id: "confidence",
    label: "Confidence",
    type: "scale",
    min: 1,
    max: 10,
    required: false,
  },
  {
    id: "pain_reported",
    label: "Any pain or injury?",
    type: "boolean",
    required: true,
    flag_above: 0,
  },
  {
    id: "readiness",
    label: "Readiness to train",
    type: "scale",
    min: 1,
    max: 10,
    required: true,
    flag_below: 4,
  },
];
